---
title: "Assignment 1: Introduction"
author: "Lauren Shohan"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have taken one R class in my undergrad which was about using R applications in Psychology, I have taken a data science class in Python, and have no experience with Git. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident in my abilities to be able to code and learn more techniques in the R language. I am excited to refresh my R skills and see what I can accomplish in this class.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel a bit apprehensive trying to use GitHub/Git, I am not sure I fully understand all the linkage between R and GitHub. All my previous classes have just been using the individual coding app and submitting a file. I feel as if I will do something wrong with pushing and committing to Git for each file and mess it all up!


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/lshohan12/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
